BOOK_FRANS = [
    {"title": "Harry Potter", "genre": "Fantasy"},
    {"title": "The Lord of the Rings", "genre": "Fantasy"},
    {"title": "Game of Thrones", "genre": "Fantasy"},
    {"title": "Percy Jackson", "genre": "Fantasy"},
    {"title": "The Hunger Games", "genre": "Dystopian"},
    {"title": "The Chronicles of Narnia", "genre": "Fantasy"},
    {"title": "The Hitchhiker's Guide to the Galaxy", "genre": "Science Fiction"},
    {"title": "The Maze Runner", "genre": "Dystopian"},
    {"title": "Discworld", "genre": "Fantasy"},
    {"title": "Dune", "genre": "Science Fiction"},
    {"title": "A Song of Ice and Fire", "genre": "Fantasy"},
    {"title": "The Wheel of Time", "genre": "Fantasy"},
    {"title": "The Expanse", "genre": "Science Fiction"},
    {"title": "Twilight", "genre": "Fantasy"},
    {"title": "The Girl with the Dragon Tattoo", "genre": "Mystery"},
    {"title": "Sherlock Holmes", "genre": "Mystery"},
    {"title": "The Shannara Chronicles", "genre": "Fantasy"},
    {"title": "The Dark Tower", "genre": "Fantasy"},
    {"title": "Foundation", "genre": "Science Fiction"},
    {"title": "The Handmaid's Tale", "genre": "Dystopian"},
    {"title": "The Martian", "genre": "Science Fiction"},
    {"title": "The Dresden Files", "genre": "Urban Fantasy"},
    {"title": "A Wrinkle in Time", "genre": "Science Fantasy"},
    {"title": "Miss Peregrine's Home for Peculiar Children", "genre": "Fantasy"},
    {"title": "The Witcher", "genre": "Fantasy"},
    {"title": "Redwall", "genre": "Fantasy"},
    {"title": "Artemis Fowl", "genre": "Fantasy"},
    {"title": "Ender's Game", "genre": "Science Fiction"},
    {"title": "The Giver", "genre": "Dystopian"},
    {"title": "His Dark Materials", "genre": "Fantasy"},
    {"title": "The 100", "genre": "Dystopian"},
    {"title": "Nancy Drew", "genre": "Mystery"},
    {"title": "Hardy Boys", "genre": "Mystery"},
    {"title": "A Series of Unfortunate Events", "genre": "Gothic Fiction"},
    {"title": "The Infernal Devices", "genre": "Steampunk"},
    {"title": "The Bartimaeus Trilogy", "genre": "Fantasy"},
    {"title": "The Southern Reach Trilogy", "genre": "Science Fiction"},
    {"title": "The Inheritance Cycle", "genre": "Fantasy"},
    {"title": "The Kingkiller Chronicle", "genre": "Fantasy"},
    {"title": "Mistborn", "genre": "Fantasy"},
    {"title": "The Belgariad", "genre": "Fantasy"},
    {"title": "The Malazan Book of the Fallen", "genre": "Fantasy"},
    {"title": "The Riyria Revelations", "genre": "Fantasy"},
    {"title": "The Broken Empire Trilogy", "genre": "Fantasy"},
    {"title": "The Stormlight Archive", "genre": "Fantasy"},
    {"title": "The Powder Mage Trilogy", "genre": "Fantasy"},
    {"title": "The Lightbringer Series", "genre": "Fantasy"},
    {"title": "The Broken Earth Trilogy", "genre": "Science Fantasy"},
    {"title": "The Grisha Trilogy", "genre": "Fantasy"},
    {"title": "The Witchlands Series", "genre": "Fantasy"},
    {"title": "The Raven Cycle", "genre": "Fantasy"},
    {"title": "The Bone Season", "genre": "Science Fiction"},
    {"title": "The Goldfinch", "genre": "Fiction"},
    {"title": "Outlander", "genre": "Historical Fiction"},
    {"title": "The Night Circus", "genre": "Fantasy"},
    {"title": "Wool", "genre": "Science Fiction"},
    {"title": "The Three-Body Problem", "genre": "Science Fiction"},
    {"title": "The Broken Girls", "genre": "Mystery"},
    {"title": "The Power", "genre": "Science Fiction"},
    {"title": "The Silent Patient", "genre": "Thriller"},
    {"title": "The Hitchhiker's Guide to the Galaxy", "genre": "Science Fiction"},
    {"title": "The Magicians", "genre": "Fantasy"},
    {"title": "The Great Gatsby", "genre": "Classic"},
    {"title": "Brave New World", "genre": "Dystopian"},
    {"title": "The Girl on the Train", "genre": "Thriller"},
    {"title": "The Da Vinci Code", "genre": "Mystery"},
    {"title": "The Alchemist", "genre": "Fiction"},
    {"title": "The Hobbit", "genre": "Fantasy"},
    {"title": "The Stand", "genre": "Horror"},
    {"title": "Frankenstein", "genre": "Gothic Fiction"},
    {"title": "To Kill a Mockingbird", "genre": "Classic"},
    {"title": "1984", "genre": "Dystopian"},
    {"title": "Dracula", "genre": "Gothic Fiction"},
    {"title": "Jurassic Park", "genre": "Science Fiction"},
    {"title": "The Handmaid's Tale", "genre": "Dystopian"},
    {"title": "The Girl with the Dragon Tattoo", "genre": "Mystery"},
    {"title": "The Godfather", "genre": "Crime"},
    {"title": "Jurassic Park", "genre": "Science Fiction"},
    {"title": "The Catcher in the Rye", "genre": "Classic"},
    {"title": "The Joy Luck Club", "genre": "Fiction"},
    {"title": "The Color Purple", "genre": "Classic"},
    {"title": "The Help", "genre": "Historical Fiction"},
    {"title": "Gone with the Wind", "genre": "Historical Fiction"},
    {"title": "The Fault in Our Stars", "genre": "Young Adult"},
    {"title": "The Maze Runner", "genre": "Dystopian"},
    {"title": "The Secret Garden", "genre": "Classic"},
    {"title": "The Diary of Anne Frank", "genre": "Biography"},
    {"title": "The Great Gatsby", "genre": "Classic"},
    {"title": "The Great Gatsby", "genre": "Classic"},
    {"title": "One Hundred Years of Solitude", "genre": "Magical Realism"},
    {"title": "The Road", "genre": "Post-Apocalyptic"},
    {"title": "The Silence of the Lambs", "genre": "Thriller"},
    {"title": "The Kite Runner", "genre": "Historical Fiction"},
    {"title": "The Count of Monte Cristo", "genre": "Adventure"},
    {"title": "The Outsiders", "genre": "Young Adult"},
    {"title": "The War of the Worlds", "genre": "Science Fiction"},
    {"title": "The Grapes of Wrath", "genre": "Historical Fiction"},
    {"title": "The Odyssey", "genre": "Epic"},
    {"title": "The Picture of Dorian Gray", "genre": "Gothic Fiction"},
    {"title": "The Jungle Book", "genre": "Children's Literature"},
    {"title": "The Sun Also Rises", "genre": "Modernist"},
    {"title": "The Secret Life of Bees", "genre": "Historical Fiction"},
    {"title": "The Wind in the Willows", "genre": "Children's Literature"},
    {"title": "The Big Sleep", "genre": "Mystery"},
    {"title": "The Odyssey", "genre": "Epic"},
    {"title": "The Time Traveler's Wife", "genre": "Science Fiction"},
    {"title": "The 5th Wave", "genre": "Science Fiction"},
    {"title": "The Book Thief", "genre": "Historical Fiction"},
    {"title": "The Road Not Taken", "genre": "Poetry"},
    {"title": "The Shadow of the Wind", "genre": "Mystery"},
    {"title": "The Sound and the Fury", "genre": "Modernist"},
    {"title": "The Metamorphosis", "genre": "Existentialism"},
    {"title": "The Fault in Our Stars", "genre": "Young Adult"},
    {"title": "The Secret Garden", "genre": "Children's Literature"},
    {"title": "The Diary of Anne Frank", "genre": "Biography"},
    {"title": "The Help", "genre": "Historical Fiction"},
    {"title": "Gone with the Wind", "genre": "Historical Fiction"},
    {"title": "The Lovely Bones", "genre": "Drama"},
    {"title": "The Old Man and the Sea", "genre": "Adventure"},
    {"title": "The Brothers Karamazov", "genre": "Philosophical Fiction"},
    {"title": "The Catcher in the Rye", "genre": "Classic"},
    {"title": "The Joy Luck Club", "genre": "Fiction"},
    {"title": "The Color Purple", "genre": "Classic"},
    {"title": "The Help", "genre": "Historical Fiction"},
    {"title": "Gone with the Wind", "genre": "Historical Fiction"},
    {"title": "The Fault in Our Stars", "genre": "Young Adult"},
    {"title": "The Maze Runner", "genre": "Dystopian"},
    {"title": "The Secret Garden", "genre": "Children's Literature"},
    {"title": "The Diary of Anne Frank", "genre": "Biography"},
    {"title": "The Martian Chronicles", "genre": "Science Fiction"},
    {"title": "The War of the Worlds", "genre": "Science Fiction"},
    {"title": "The Name of the Wind", "genre": "Fantasy"},
    {"title": "The Lies of Locke Lamora", "genre": "Fantasy"},
    {"title": "The Magicians", "genre": "Fantasy"},
    {"title": "The Girl on the Train", "genre": "Thriller"},
    {"title": "The Da Vinci Code", "genre": "Mystery"},
    {"title": "The Alchemist", "genre": "Fiction"},
    {"title": "The Hobbit", "genre": "Fantasy"},
    {"title": "The Stand", "genre": "Horror"},
    {"title": "Frankenstein", "genre": "Gothic Fiction"},
    {"title": "To Kill a Mockingbird", "genre": "Classic"},
    {"title": "1984", "genre": "Dystopian"},
    {"title": "Dracula", "genre": "Gothic Fiction"},
    {"title": "Jurassic Park", "genre": "Science Fiction"},
    {"title": "The Handmaid's Tale", "genre": "Dystopian"},
    {"title": "The Girl with the Dragon Tattoo", "genre": "Mystery"},
    {"title": "The Godfather", "genre": "Crime"},
    {"title": "Jurassic Park", "genre": "Science Fiction"},
    {"title": "The Catcher in the Rye", "genre": "Classic"},
    {"title": "The Joy Luck Club", "genre": "Fiction"},
    {"title": "The Color Purple", "genre": "Classic"},
    {"title": "The Help", "genre": "Historical Fiction"},
    {"title": "Gone with the Wind", "genre": "Historical Fiction"},
    {"title": "The Fault in Our Stars", "genre": "Young Adult"},
    {"title": "The Maze Runner", "genre": "Dystopian"},
    {"title": "The Secret Garden", "genre": "Children's Literature"},
    {"title": "The Diary of Anne Frank", "genre": "Biography"},
    {"title": "The Martian Chronicles", "genre": "Science Fiction"},
    {"title": "The War of the Worlds", "genre": "Science Fiction"},
    {"title": "The Name of the Wind", "genre": "Fantasy"},
    {"title": "The Lies of Locke Lamora", "genre": "Fantasy"},
    {"title": "The Magicians", "genre": "Fantasy"},
    {"title": "The Girl on the Train", "genre": "Thriller"},
    {"title": "The Da Vinci Code", "genre": "Mystery"},
    {"title": "The Alchemist", "genre": "Fiction"},
    {"title": "The Hobbit", "genre": "Fantasy"},
    {"title": "The Stand", "genre": "Horror"},
    {"title": "Frankenstein", "genre": "Gothic Fiction"},
    {"title": "To Kill a Mockingbird", "genre": "Classic"},
    {"title": "1984", "genre": "Dystopian"},
    {"title": "Dracula", "genre": "Gothic Fiction"},
    {"title": "Jurassic Park", "genre": "Science Fiction"},
    {"title": "The Handmaid's Tale", "genre": "Dystopian"},
    {"title": "The Girl with the Dragon Tattoo", "genre": "Mystery"},
    {"title": "The Godfather", "genre": "Crime"},
]


def make_list_of_dicts_unique(input_list, key):
    seen = set()
    unique_list = []
    for d in input_list:
        if d[key] not in seen:
            seen.add(d[key])
            unique_list.append(d)
    return unique_list


BOOKS_M = make_list_of_dicts_unique(BOOK_FRANS, key="title")

print(len(BOOKS_M))
